name: Deploy Astro to CentOS 9

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20


      - name: Build Astro
        run: |
          npm install
          npm run build  # 输出到 dist/ 目录

 
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |

            cd /var/www/blog

            rm -rf !(.env|.htaccess)

            rsync -avz --delete $GITHUB_WORKSPACE/dist/ .
